let countryExt = [
    ['Afghanistan', "^\\d{4}$"],
     ['Albania',   ('\\d{4}')],
     ['American Samoa',   ('\\d{5}')],
     ['Andorra',   ('(?:AD)(\\d{3})')],
     ['Antigua & Barbuda',   ('\\d{5}')],
     ['Argentina',   ('([A-Z]\\d{4}[A-Z]{3})|([A-Z]\\d{4})')],
     ['Armenia',   ('(\\d{4})|(\\d{6})')],
     ['Aruba',   ('')],
     ['Australia',   ('\\d{4}')],
     ['Austria',   ('\\d{4}')],
     ['Azerbaijan',   ('(AZ) (\\d{4})')],
     ['Bahamas',   ('')],
     ['Bahrain',   ('\\d{3}\d?')],
     ['Bangladesh',   ('\\d{4}')],
     ['Barbados',   ('(?:BB)(\\d{5})')],
     ['Belarus',   ('\\d{6}')],
     ['Belgium',   ('\\d{4}')],
     ['Belize',   ('')],
     ['Benin',   ('')],
     ['Bermuda',   ('[A-Z]{2} \\d{2}')],
     ['Bhutan',   ('\\d{5}')],
     ['Bolivia',   ('')],
     ['Bonaire',   ('')],
     ['Bosnia & Herzegovina',   ('\\d{5}')],
     ['Botswana',   ('')],
     ['Brazil',   ('[0-9]{5}-[0-9]{3}')],
     ['Brunei',   ('[A-Z]{2}\\d{4}')],
     ['Bulgaria',   ("^\\d{4}$")],
     ['Burkina Faso',   ('')],
     ['Burundi',   ('')],
     ['Cambodia',   ('\\d{5}')],
     ['Cameroon',   ('')],
     ['Canada',   ('')],
     ['Cayman Islands',   ('[K][Y][0-9]{1}[-]([0-9]){4}')],
     ['Central African Republic',   ('')],
     ['Chad',   ('')],
     ['Chile',   ('\\d{7}')],
     ['China',   ('\\d{6}')],
     ['Christmas Island"',   ('(6798)')],
     ['Cocos Island',   ('(6799)')],
     ['Colombia',   ('\\d{6}')],
     ['Comoros',   ('')],
     ['Congo',   ('')],
     ['Cook Islands',   ('')],
     ['Costa Rica',   ('\\d{5}')],
     ['Cote D\'voire',   ('')],
     ['Croatia',   ('\\d{5}')],
     ['Cuba',   ('(?:CP)(\\d{5})')], 
     ['Curacao',   ('')],
     ['Cyprus',   '\\d{4}'],
     ['Czech Republic',   ('[0-9]{3} [0-9]{2}|[0-9]{5}')],
     ['Denmark',   ('\\d{4}')],
     ['Djibouti',   ('')],
     ['Dominica',   ('')],
     ['Dominican Republic',   ('\\d{5}')],
     ['Ecuador',   ('\\d{6}')],
     ['Egypt',   ('\\d{5}')],
     ['El Salvador',   ('((CP) \\d{4})')],
     ['Equatorial Guinea',   ('')],
     ['Eritrea',   ('')],
     ['Estonia',   ('\\d{5}')],
     ['Ethiopia',   ('\\d{4}')],
     ['Falkland Islands',   ('(FIQQ 1ZZ)')],
     ['Faroe Islands',   ('\\d{3}')],
     ['Fiji',   ('')],
     ['Finland',   ('\\d{5}')],
     ['France',   ('\\d{5}')],
     ['French Guiana',   ('\\d{5}')],
     ['French Polynesia',   ('((987)\\d{2})')],
     ['French Southern Ter',   ('((984)\\d{2})')],
     ['Gabon',   ('')],
     ['Gambia',   ('')],
     ['Georgia',   ('\\d{4}')],
     ['Germany',   ('\\d{5}')],
     ['Ghana',   ('')],
     ['Gibraltar',   ('(GX11 1AA)')],
     ['Greece',   ('(\\d{3}) \\d{2}|\\d{5}')],
     ['Greenland',   ('\\d{4}')],
     ['Grenada',   ('')],
     ['Guadeloupe',   ('\\d{5}')],
     ['Guam',   ('((969)[1-3][0-2])')],
     ['Guatemala',   ('\\d{5}')],
     ['Guinea',   ('\\d{3}')],
     ['Guyana',   ('')],
     ['Haiti',   ('(?:HT)(\\d{4})')],
     ['Honduras',   ('\\d{5}')],
     ['Hong Kong',   ('(999077)')],
     ['Hungary',   ('\\d{4}')],
     ['Iceland',   ('\\d{3}')],
     ['Indonesia',   ('\\d{5}')],
     ['India',   ('\\d{6}')],
     ['Iran',   ('\\d{5}[\-]?\\d{5}')],
     ['Iraq',   ('\\d{5}')],
     ['Ireland',   ('')],
     ['Isle of Man',   ('(IM)([0-9][0-9A-HJKPS-UW]?|[A-HK-Y][0-9][0-9ABEHMNPRV-Y]?) [0-9][ABD-HJLNP-UW-Z]{2}')],
     ['Israel',   ('\\d{7}')],
     ['Italy',   ('\\d{5}')],
     ['Jamaica',   ('(JM)[A-Z]{3}\\d{2}')],
     ['Japan',   ('(\\d{3}-\\d{4})')],
     ['Jordan',   ('\\d{5}')],
     ['Kazakhstan',   ('\\d{6}')],
     ['Kenya',   ('\\d{5}')],
     ['Kiribati',   ('')],
     ['Korea North',   ('')],
     ['Korea South',   ('')],
     ['Kuwait',   ('\\d{5}')],
     ['Kyrgyzstan',   ('\\d{6}')],
     ['Laos',   ('^\\d{5}$')],
     ['Latvia',   ('[L]{1}[V]{1}[-]([0-9]){4}')],
     ['Lebanon',   ('\\d{4}( \\d{4})?')],
     ['Lesotho',   ('\\d{3}')],
     ['Liberia',   ('\\d{4}')],
     ['Libya',   ('')],

     ['Liechtenstein',   ('\\d{4}')],
     ['Lithuania',   ('((?:LT)[\-])?(\\d{5})')],
     ['Luxembourg',   ('((?:L)[\-])?(\\d{4})')],
     ['Macedonia',   ('\\d{4}')],
     ['Madagascar',   ('\\d{3}')],
     ['Malaysia',   ('\\d{5}')],
     ['Malawi',   ('')],
     ['Maldives',   ('\\d{5}')],
     ['Mali',   ('')],
     ['Malta',   ('[A-Z]{3} [0-9]{4}|[A-Z]{2}[0-9]{2}|[A-Z]{2} [0-9]{2}|[A-Z]{3}[0-9]{4}|[A-Z]{3}[0-9]{2}|[A-Z]{3} [0-9]{2}')],
     ['Marshall Islands',   ('((969)[6-7][0-9])')],
     ['Martinique',   ('\\d{5}')],
     ['Mauritania',   ('')],
     ['Mauritius',   ('([0-9A-Z]\\d{4})')],
     ['Mayotte',   ('\\d{5}')],
     ['Mexico',   ('\\d{5}')],
     ['Moldova',   ('\\d{5}')],
     ['Monaco',   ('\\d{5}')],
     ['Mongolia',   ('\\d{5}')],
     ['Montserrat',   ('(?:MSR )(\\d{4})')],
     ['Morocco',   ('\\d{5}')],
     ['Mozambique',   ('\\d{4}')],
     ['Myanmar',   ('\\d{5}')],
     ['Nauru',   ('')],
     ['Nepal',   ('\\d{5}')],
     ['Netherlands',   ('[0-9]{4} [A-Z]{2}|[0-9]{4}[A-Z]{2}')],
     ['Nevis',   ('')],
     ['New Caledonia',   ('\\d{5}')],
     ['New Zealand',   ('\\d{4}')],
     ['Nicaragua',   ('\\d{5}')],
     ['Niger',   ('\\d{4}')],
     ['Nigeria',   ('\\d{6}')],
     ['Niue',   ('')],
     ['Norfolk Island',   ('(2899)')],
     ['Norway',   ('\\d{4}')],
     ['Oman',   ('\\d{3}')],
     ['Pakistan',   ('\\d{5}')],
     ['Palestine',   ('(\\d{3}-\\d{3})')],
     ['Panama',   ('')],
     ['Papua New Guinea',   ('\\d{3}')],
     ['Paraguay',   ('\\d{4}')],
     ['Peru',   ('\\d{5}')],
     ['Philippines',   ('\\d{4}')],
     ['Poland',   ('[0-9]{2}[-]([0-9]){3}')],
     ['Portugal',   ('\\d{4}((-)\\d{3})')],
     ['Puerto Rico',   ('[0-9]{5}(?:-[0-9]{4})?')],
     ['Qatar',   ('')],
     ['Republic of Montenegro',   ('\\d{5}')],
     ['Republic of Serbia',   ('\\d{5}')],
     ['Reunion',   ('\\d{5}')],
     ['Romania',   ('\\d{6}')],
     ['Russia',   ('\\d{6}')],
     ['Rwanda',   ('')],
     ['St Barthelemy',   ('\\d{5}')],
     ['St Eustatius',   ('')],
     ['St Helena',   ('')],
     ['St Lucia',   ('')],
     ['St Maarten',   ('')],
     ['St Vincent & Grenadines',   ('(VC)(\\d{4})')],
     ['Samoa',   ('(96799)')],
     ['San Marino',   ('(4789\d)')],
     ['Sao Tome & Principe',   ('')],
     ['Saudi Arabia',   ('\\d{5}([\-]\\d{4})?')],
     ['Senegal',   ('\\d{5}')],
     ['Seychelles',   ('')],
     ['Sierra Leone',   ('')],
     ['Singapore',   ('\\d{6}')],
     ['Slovakia',   ('(\\d{3} \\d{2})|\\d{5}')],
     ['Slovenia',   ('\\d{4}')],
     ['Solomon Islands',   ('')],
     ['Somalia',   ('')],
     ['South Africa',   ('\\d{4}')],
     ['Spain',   ('\\d{5}')],
     ['Sri Lanka',   ('\\d{5}')],
     ['Sudan',   ('\\d{5}')],
     ['Suriname',   ('')],
     ['Swaziland',   ('([A-Z]\\d{3})')],
     ['Sweden',   ('(\\d{3} \\d{2})')],
     ['Switzerland',   ('\\d{4}')],
     ['Syria',   ('')],
     ['Taiwan',   ('(\\d{3}[-]\\d{2})|(\\d{3})')],
     ['Tajikistan',   ('\\d{3}')],
     ['Tanzania',   ('\\d{5}')],
     ['Thailand',   ('\\d{5}')],
     ['Togo',   ('')],
     ['Tokelau',   ('')],
     ['Tonga',   ('')],
     ['Trinidad & Tobago', ('')],
     ['Tunisia',   ('\\d{4}')],
     ['Turkey',   ('\\d{5}')],
     ['Turkmenistan',   ('\\d{6}')],
     ['Turks & Caicos Is',   ('(TKCA 1ZZ)')],
     ['Tuvalu',   ('')],
     ['Uganda',   ('')],
     ['United Kingdom',   ('([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z])))) [0-9][A-Za-z]{2})')],
     ['Ukraine',   ('\\d{5}')],
     ['United Arab Erimates',   ('')],
     ['United States of America',   ('[0-9]{5}(?:-[0-9]{4})?')],
     ['Uruguay',   ('\\d{5}')],
     ['Uzbekistan',   ('\\d{6}')],
     ['Vanuatu',   ('')],
     ['Venezuela',   ('\\d{4}')],
     ['Vietnam',   ('^\\d{6}$')],
     ['Virgin Islands (Brit)',   ('(VG11)[0-6][0]')],
     ['Virgin Islands (USA)',   ('\\d{5}')],
     ['Wallis & Futana Is',   ('((986)\\d{2})')],
     ['Yemen',   ('')],
     ['Zambia',   ('\\d{5}')],
     ['Zimbabwe',   ('')]]