let countryExt = [
    ['Afghanistan', new RegExp("^\\d{4}$")],
     ['Albania',   new RegExp('\\d{4}')],
     ['American Samoa',   new RegExp('\\d{5}')],
     ['Andorra',   new RegExp('(?:AD)(\\d{3})')],
     ['Antigua & Barbuda',   new RegExp('\\d{5}')],
     ['Argentina',   new RegExp('([A-Z]\\d{4}[A-Z]{3})|([A-Z]\\d{4})')],
     ['Armenia',  new RegExp ('(\\d{4})|(\\d{6})')],
     ['Aruba',   new RegExp('')],
     ['Australia',   new RegExp('\\d{4}')],
     ['Austria',   new RegExp('\\d{4}')],
     ['Azerbaijan',   new RegExp('(AZ) (\\d{4})')],
     ['Bahamas',   new RegExp('')],
     ['Bahrain',   new RegExp('\\d{3}\d?')],
     ['Bangladesh',   new RegExp('\\d{4}')],
     ['Barbados',  new RegExp ('(?:BB)(\\d{5})')],
     ['Belarus',   new RegExp('\\d{6}')],
     ['Belgium',   new RegExp('\\d{4}')],
     ['Belize',   new RegExp('')],
     ['Benin',   new RegExp('')],
     ['Bermuda',   new RegExp('[A-Z]{2} \\d{2}')],
     ['Bhutan',   new RegExp('\\d{5}')],
     ['Bolivia',   new RegExp('')],
     ['Bonaire',   new RegExp('')],
     ['Bosnia & Herzegovina',   new RegExp('\\d{5}')],
     ['Botswana',   new RegExp('')],
     ['Brazil',   new RegExp('[0-9]{5}-[0-9]{3}')],
     ['Brunei',   new RegExp('[A-Z]{2}\\d{4}')],
     ['Bulgaria',   new RegExp("^\\d{4}$")],
     ['Burkina Faso',  new RegExp ('')],
     ['Burundi',  new RegExp ('')],
     ['Cambodia',  new RegExp ('\\d{5}')],
     ['Cameroon',  new RegExp ('')],
     ['Canada',   new RegExp('')],
     ['Cayman Islands',  new RegExp ('[K][Y][0-9]{1}[-]([0-9]){4}')],
     ['Central African Republic',  new RegExp ('')],
     ['Chad',  new RegExp ('')],
     ['Chile',   new RegExp('\\d{7}')],
     ['China',  new RegExp ('\\d{6}')],
     ['Christmas Island"',  new RegExp ('(6798)')],
     ['Cocos Island',  new RegExp ('(6799)')],
     ['Colombia',  new RegExp ('\\d{6}')],
     ['Comoros',   new RegExp('')],
     ['Congo',   new RegExp('')],
     ['Cook Islands',  new RegExp ('')],
     ['Costa Rica',  new RegExp ('\\d{5}')],
     ['Cote D\'voire',  new RegExp ('')],
     ['Croatia',   new RegExp('\\d{5}')],
     ['Cuba',   ('(?:CP)(\\d{5})')], 
     ['Curacao',   ('')],
     ['Cyprus',   new RegExp('\\d{4}')],
     ['Czech Republic',   new RegExp('[0-9]{3} [0-9]{2}|[0-9]{5}')],
     ['Denmark',   new RegExp('\\d{4}')],
     ['Djibouti',   new RegExp('')],
     ['Dominica',   new RegExp('')],
     ['Dominican Republic',  new RegExp ('\\d{5}')],
     ['Ecuador',  new RegExp ('\\d{6}')],
     ['Egypt',  new RegExp ('\\d{5}')],
     ['El Salvador',   new RegExp('((CP) \\d{4})')],
     ['Equatorial Guinea',   new RegExp('')],
     ['Eritrea',   new RegExp('')],
     ['Estonia',   new RegExp('\\d{5}')],
     ['Ethiopia',   new RegExp('\\d{4}')],
     ['Falkland Islands',   new RegExp('(FIQQ 1ZZ)')],
     ['Faroe Islands',   new RegExp('\\d{3}')],
     ['Fiji',   new RegExp('')],
     ['Finland',   new RegExp('\\d{5}')],
     ['France',  new RegExp ('\\d{5}')],
     ['French Guiana',   new RegExp('\\d{5}')],
     ['French Polynesia',   new RegExp('((987)\\d{2})')],
     ['French Southern Ter',  new RegExp ('((984)\\d{2})')],
     ['Gabon',   new RegExp('')],
     ['Gambia',   new RegExp('')],
     ['Georgia',   new RegExp('\\d{4}')],
     ['Germany',   new RegExp('\\d{5}')],
     ['Ghana',   new RegExp('')],
     ['Gibraltar',   new RegExp('(GX11 1AA)')],
     ['Greece',   new RegExp('(\\d{3}) \\d{2}|\\d{5}')],
     ['Greenland',   new RegExp('\\d{4}')],
     ['Grenada',  new RegExp ('')],
     ['Guadeloupe',   new RegExp('\\d{5}')],
     ['Guam',   new RegExp('((969)[1-3][0-2])')],
     ['Guatemala',   new RegExp('\\d{5}')],
     ['Guinea',   new RegExp('\\d{3}')],
     ['Guyana',   new RegExp('')],
     ['Haiti',   new RegExp('(?:HT)(\\d{4})')],
     ['Honduras',   new RegExp('\\d{5}')],
     ['Hong Kong',   new RegExp('(999077)')],
     ['Hungary',   new RegExp('\\d{4}')],
     ['Iceland',   new RegExp('\\d{3}')],
     ['Indonesia',   new RegExp('\\d{5}')],
     ['India',   new RegExp('\\d{6}')],
     ['Iran',   new RegExp('\\d{5}[\-]?\\d{5}')],
     ['Iraq',  new RegExp ('\\d{5}')],
     ['Ireland',   new RegExp('')],
     ['Isle of Man',   new RegExp('(IM)([0-9][0-9A-HJKPS-UW]?|[A-HK-Y][0-9][0-9ABEHMNPRV-Y]?) [0-9][ABD-HJLNP-UW-Z]{2}')],
     ['Israel',   new RegExp('\\d{7}')],
     ['Italy',   new RegExp('\\d{5}')],
     ['Jamaica',   new RegExp('(JM)[A-Z]{3}\\d{2}')],
     ['Japan',   new RegExp('(\\d{3}-\\d{4})')],
     ['Jordan',   new RegExp('\\d{5}')],
     ['Kazakhstan',   new RegExp('\\d{6}')],
     ['Kenya',   new RegExp('\\d{5}')],
     ['Kiribati',   new RegExp('')],
     ['Korea North',   new RegExp('')],
     ['Korea South',   new RegExp('')],
     ['Kuwait',   new RegExp('\\d{5}')],
     ['Kyrgyzstan',   new RegExp('\\d{6}')],
     ['Laos',  new RegExp ('^\\d{5}$')],
     ['Latvia',  new RegExp ('[L]{1}[V]{1}[-]([0-9]){4}')],
     ['Lebanon',  new RegExp ('\\d{4}( \\d{4})?')],
     ['Lesotho',   new RegExp('\\d{3}')],
     ['Liberia',   new RegExp('\\d{4}')],
     ['Libya',   new RegExp('')],

     ['Liechtenstein',   new RegExp('\\d{4}')],
     ['Lithuania',   new RegExp('((?:LT)[\-])?(\\d{5})')],
     ['Luxembourg',   new RegExp('((?:L)[\-])?(\\d{4})')],
     ['Macedonia',   new RegExp('\\d{4}')],
     ['Madagascar',   new RegExp('\\d{3}')],
     ['Malaysia',   new RegExp('\\d{5}')],
     ['Malawi',   new RegExp('')],
     ['Maldives',   new RegExp('\\d{5}')],
     ['Mali',   new RegExp('')],
     ['Malta',   new RegExp('[A-Z]{3} [0-9]{4}|[A-Z]{2}[0-9]{2}|[A-Z]{2} [0-9]{2}|[A-Z]{3}[0-9]{4}|[A-Z]{3}[0-9]{2}|[A-Z]{3} [0-9]{2}')],
     ['Marshall Islands',   new RegExp('((969)[6-7][0-9])')],
     ['Martinique',  new RegExp ('\\d{5}')],
     ['Mauritania',  new RegExp ('')],
     ['Mauritius',   new RegExp('([0-9A-Z]\\d{4})')],
     ['Mayotte',   new RegExp('\\d{5}')],
     ['Mexico',  new RegExp ('\\d{5}')],
     ['Moldova',   new RegExp('\\d{5}')],
     ['Monaco',   new RegExp('\\d{5}')],
     ['Mongolia',  new RegExp ('\\d{5}')],
     ['Montserrat',   new RegExp('(?:MSR )(\\d{4})')],
     ['Morocco',   new RegExp('\\d{5}')],
     ['Mozambique',  new RegExp ('\\d{4}')],
     ['Myanmar',   new RegExp('\\d{5}')],
     ['Nauru',   new RegExp('')],
     ['Nepal',   new RegExp('\\d{5}')],
     ['Netherlands',  new RegExp ('[0-9]{4} [A-Z]{2}|[0-9]{4}[A-Z]{2}')],
     ['Nevis',   new RegExp('')],
     ['New Caledonia',   new RegExp('\\d{5}')],
     ['New Zealand',   new RegExp('\\d{4}')],
     ['Nicaragua',   new RegExp('\\d{5}')],
     ['Niger',   new RegExp('\\d{4}')],
     ['Nigeria',   new RegExp('\\d{6}')],
     ['Niue',   new RegExp('')],
     ['Norfolk Island',  new RegExp ('(2899)')],
     ['Norway',  new RegExp ('\\d{4}')],
     ['Oman',   new RegExp('\\d{3}')],
     ['Pakistan',  new RegExp ('\\d{5}')],
     ['Palestine',   new RegExp('(\\d{3}-\\d{3})')],
     ['Panama',   new RegExp('')],
     ['Papua New Guinea',   new RegExp('\\d{3}')],
     ['Paraguay',  new RegExp ('\\d{4}')],
     ['Peru',  new RegExp ('\\d{5}')],
     ['Philippines',   new RegExp('\\d{4}')],
     ['Poland',   new RegExp('[0-9]{2}[-]([0-9]){3}')],
     ['Portugal',  new RegExp ('\\d{4}((-)\\d{3})')],
     ['Puerto Rico',   new RegExp('[0-9]{5}(?:-[0-9]{4})?')],
     ['Qatar',  new RegExp ('')],
     ['Republic of Montenegro',   new RegExp('\\d{5}')],
     ['Republic of Serbia',   new RegExp('\\d{5}')],
     ['Reunion',   new RegExp('\\d{5}')],
     ['Romania',   new RegExp('\\d{6}')],
     ['Russia',   new RegExp('\\d{6}')],
     ['Rwanda',   new RegExp('')],
     ['St Barthelemy',   new RegExp('\\d{5}')],
     ['St Eustatius',   new RegExp('')],
     ['St Helena',   new RegExp('')],
     ['St Lucia',   new RegExp('')],
     ['St Maarten',   new RegExp('')],
     ['St Vincent & Grenadines',   new RegExp('(VC)(\\d{4})')],
     ['Samoa',   new RegExp('(96799)')],
     ['San Marino',   new RegExp('(4789\d)')],
     ['Sao Tome & Principe',   new RegExp('')],
     ['Saudi Arabia',   new RegExp('\\d{5}([\-]\\d{4})?')],
     ['Senegal',   new RegExp('\\d{5}')],
     ['Seychelles',   new RegExp('')],
     ['Sierra Leone',   new RegExp('')],
     ['Singapore',   new RegExp('\\d{6}')],
     ['Slovakia',   new RegExp('(\\d{3} \\d{2})|\\d{5}')],
     ['Slovenia',   new RegExp('\\d{4}')],
     ['Solomon Islands',   new RegExp('')],
     ['Somalia',   new RegExp('')],
     ['South Africa',   new RegExp('\\d{4}')],
     ['Spain',   new RegExp('\\d{5}')],
     ['Sri Lanka',   new RegExp('\\d{5}')],
     ['Sudan',   new RegExp('\\d{5}')],
     ['Suriname',   new RegExp('')],
     ['Swaziland',   new RegExp('([A-Z]\\d{3})')],
     ['Sweden',   new RegExp('(\\d{3} \\d{2})')],
     ['Switzerland',   new RegExp('\\d{4}')],
     ['Syria',   new RegExp('')],
     ['Taiwan',   new RegExp('(\\d{3}[-]\\d{2})|(\\d{3})')],
     ['Tajikistan',   new RegExp('\\d{3}')],
     ['Tanzania',   new RegExp('\\d{5}')],
     ['Thailand',   ('\\d{5}')],
     ['Togo',   new RegExp('')],
     ['Tokelau',   new RegExp('')],
     ['Tonga',   new RegExp('')],
     ['Trinidad & Tobago', new RegExp('')],
     ['Tunisia',   new RegExp('\\d{4}')],
     ['Turkey',   new RegExp('\\d{5}')],
     ['Turkmenistan',   new RegExp('\\d{6}')],
     ['Turks & Caicos Is',   new RegExp('(TKCA 1ZZ)')],
     ['Tuvalu',   new RegExp('')],
     ['Uganda',   new RegExp('')],
     ['United Kingdom',   new RegExp('([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z])))) [0-9][A-Za-z]{2})')],
     ['Ukraine',   new RegExp('\\d{5}')],
     ['United Arab Erimates',   new RegExp('')],
     ['United States of America',   new RegExp('[0-9]{5}(?:-[0-9]{4})?')],
     ['Uruguay',   new RegExp('\\d{5}')],
     ['Uzbekistan',   new RegExp('\\d{6}')],
     ['Vanuatu',   new RegExp('')],
     ['Venezuela',   new RegExp('\\d{4}')],
     ['Vietnam',   new RegExp('^\\d{6}$')],
     ['Virgin Islands (Brit)',   new RegExp('(VG11)[0-6][0]')],
     ['Virgin Islands (USA)',   new RegExp('\\d{5}')],
     ['Wallis & Futana Is',   new RegExp('((986)\\d{2})')],
     ['Yemen',  new RegExp ('')],
     ['Zambia',   new RegExp('\\d{5}')],
     ['Zimbabwe',   new RegExp('')]]